### ISSUE TITLE
Report regroupé: raison des lags(supposition), aspect esthétique du niveau 2 et 3, problème de solidité niveau 1, glitch des darthuro sur la lave.

### ISSUE THREAD

**Issue by Leo1417** [PhonArt/Pixel-Knight#23]
Raison du lag du jeu :les ups plus y'en a plus y'a de prbl
-Il faudrait rajouter une ligne noir niv2
-niv1 mur immatériel
-niv3 faudrait potentiellement baissé la grotte du coffre
-niv4 les monstres peuvent tombé et son glitch sur la lave
-niv5/6 darthuro va sur la plateforme et tombe sur la lave et marche dessus
-Autre raison de lag la mort des araignées

**Comment by PhonArt** [comment]
Tous les bugs ont été corrigés.
Merci d'attendre la prochaine mise à jour.
