### ISSUE TITLE
Chute des monstres

### ISSUE THREAD

**Issue by Leo1417** [PhonArt/Pixel-Knight#33]
A cause des sauts des firebowl ils tombent dans la lave ou sur d'autre plateformes.
De plus les darthuro montent sur les plateformes mouvantes et tombent sur la lave.

**Comment by PhonArt** [comment]
Bonjour, 

Le bug concernant les ennemis marchants sur les plateformes devrait être corrigé. En revanche, le problème concernant les Firebowl ne sera pas fixé tout de suite car leur intelligence artificiel sera modifié.

Cordialement,
PhonArt.
