### ISSUE TITLE
Son parasite a la fin du niveau

### ISSUE THREAD

**Issue by Leo1417** [PhonArt/Pixel-Knight#34]
Quand on fini un niveau ou la fin est suivi d'une fin de plateforme menant sur la lave le personnage continu a avancer et tombe dans la lave provoquant le son de mort.

**Comment by PhonArt** [comment]
Bonjour,

Ce bug devrait maintenant être corrigé. Si jamais il ne l'est pas, merci de réouvrir cet Issues et de ne pas en créer un nouveau.

Cordialement,
PhonArt.
